[build]
target = "../rv32imac-cfi-none-elf.json"

[target.'cfg(target_arch = "riscv32")']
runner = "qemu-system-riscv32 -machine virt -nographic -bios none -kernel"
rustflags = [
    "-C", "link-arg=-Tmemory.x",
    "-C", "link-arg=-Tlink.x",
    "-C", "link-arg=--no-relax",
]

[unstable]
build-std = ["core"]
build-std-features = ["compiler-builtins-mem"]
json-target-spec = true
